### ISSUE TITLE
Proposal: Alternatives for ArrayVec and SliceVec that internally use `Option` so elements do not need the `Default` trait

### ISSUE THREAD

**Issue by Qqwy** [Lokathor/tinyvec#155]
ArrayVec,SliceVec and TinyVec are great containers, as long as your element type T implements the `Default` trait.

For types that do not (examples: many`enum` types, some pointer types, etc.), a simple way to still allow them to be used is to wrap them into an `Option<T>`.
However, when we use this technique to store `T`'s inside, i.e. we store `Some(T)`'s to make the API work,
we end up having to `.unwrap()` these each time we read them from the collection as well.

Maybe we could add collections that rather than require the `Default` trait, are able to wrap any `T` and perform the wrapping/unwrapping of `Some` internally automatically.

What do you think?

**Comment by Lokathor** [comment]
Hmm, I like the basic idea.

I'm not sure how ergonomic it would end up being. For example, if the collection stores a bunch of `Option<T>` then you can't just get a slice to `&[T]` because in the general case the layout won't match. Since you can't deref into a slice a lot of "free" compatibility with `core` isn't there.

I'm happy to look at some concrete code. I've never needed this myself but I'm not against the idea of providing such a container (though probably behind an "experimental" flag for at least a while).

**Comment by Shnatsel** [comment]
This has previously been discussed in #70, but the lack of slicing again came up as a major limitation, and ultimately nobody pursued it.

**Comment by Qqwy** [comment]
Thank you both for your responses.

Limiting slice-support would indeed very much limit its usefulness, also for the circumstance I was hoping to use it for.

So I will be closing this.

P.S. I had a look at some of the source code of `tinyvec` and need to say: @Lokathor what a well-written library! :smile:
