### ISSUE TITLE
Clarify crate goals and crate stability

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/tinyvec#18]
The `lib.rs` should clearly state the three long term goals of the crate:

* never use `unsafe`
  * Not even `unsafe` that we 100% know is sound.
  * No `unsafe` at all.
  * that's what sets us apart as a crate!
* never require dependencies beyond the standard library
  * either they're pure safe, in which case we can generally do whatever thing ourselves, or they're `unsafe` in which case we don't want it, per the hard line rule above.
  * I could imagine eventual _optional_ dependencies as long as they always stay off by default. Such as `serde` support.
* be as close to a drop-in replacement for `alloc::vec::Vec` as possible.
  * All methods with the same name as `Vec` methods should act as closely as possible to the `Vec` version.
  * Support nightly `Vec` methods where possible via features also marked as being nightly
  * Provide extra methods beyond what `Vec` does very carefully so that we hopefully don't collide with potential future `Vec` methods (this part is impossible to assure, but it's worth saying that we're trying).

**Comment by Shnatsel** [comment]
I'm not 100% sold on "no dependencies, even safe ones" - e.g. we might eventually want to pull in something like `static-assertions` without reimplementing it. It's a good guideline, but I'm not sold on it as an ironclad rule.

Other than that looks good. Very good point on not providing methods beyond what Vec supports so that we wouldn't collide.
