### ISSUE TITLE
Rename TinyVecIterator to IntoIter

### ISSUE THREAD

**Issue by Nemo157** [Lokathor/tinyvec#53]
The current naming is inconsistent with all other collection types. I'm not sure what to do about having `ArrayVecIterator` as well, I'd be tempted to say that `ArrayVec`'s associated types should be moved into a module since that's not the titular data-type.

**Comment by Lokathor** [comment]
I'm also adding a third vec type now (slicevec) and it will _also_ have iterators and drains and such.

I think that I'm willing to just eat the minor difference in naming here, if other people are okay with it.

I'd rather that the library overall have as flat of a module structure as possible with slightly more verbose names, instead of having all sorts of sub-modules. I mean, I know it's technically against the Rust API guidelines to have `my_crate::IoError` instead of `my_crate::io::Error`, but that's honestly the worst RFC Rust has ever put through. Flat crates and proper names is just better.

Particularly, the iterator types of various sorts are usually never _named_ by actual user code, there's just type inference. In other words, usually code is more like
```rust
for d in ar.drain(..) { }
```

than like

```rust
let mut array_drain: Drain<T> = ar.drain(..);
```

Sound reasonable?

**Comment by Nemo157** [comment]
I seem to name iterator types not _that_ infrequently, maybe once or twice a year in order to put them inside structs.

But it's also not ta big deal, just a small papercut if you're writing code assuming standard layouts instead of checking actual names (which is why I noticed this).

**Comment by Lokathor** [comment]
Alright, closing this one then.
